GET http://localhost:3000/items

###

GET http://localhost:3000/items/65daf61e145c3f51b1a6b8e2

###

POST http://localhost:3000/items
Content-Type: application/json

{
    "name": "Red Stapler",
    "type": "Indoors"
}

###

DELETE  http://localhost:3000/items/65daf390e89caf675edc0b80